### ISSUE TITLE
op fusion only, or do codegen like tvm ?

### ISSUE THREAD

**Issue by ZongqiangZhang** [mindspore-ai/akg#1]
i am not sure the roadmap of AKG. It will focus on op fusion only, or do kernel codegen just like TVM.

**Comment by RyanWhb** [comment]
AKG supports kernel generation for Ascend and GPU platform now，u can develop operators by using TVM DSL.

**Comment by RyanWhb** [comment]
> i am not sure the roadmap of AKG. It will focus on op fusion only, or do kernel codegen just like TVM.
AKG supports kernel generation for Ascend and GPU platform now，u can develop operators by using TVM DSL.

**Comment by leonwanghui** [comment]
@ZongqiangZhang  This issue would be closed, please be free to reopen if you have any question, thanks!
